'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:38 pm'!


!Closure methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
asCallback
	<primitive: ClosureAsCallback>
! !

!Closure methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
value
	<primitive: ClosureValue>
! !

!Closure methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
evaluateAtomically
	<primitive: ClosureValue>
! !

!Closure methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
value: arg1
	<primitive: ClosureValueWithArgs>
! !

!Closure methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
value: arg1 value: arg2
	<primitive: ClosureValueWithArgs>
! !

!Closure methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
value: arg1 value: arg2 value: arg3
	<primitive: ClosureValueWithArgs>
! !

!Closure methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
evaluateWith: arg1
	<primitive: ClosureValueWithArgs>
! !

!Closure methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
evaluateWith: arg1 with: arg2
	<primitive: ClosureValueWithArgs>
! !

!Closure methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
argumentCount
	<primitive: ClosureArgumentCount>
! !


