'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:38 pm'!


!ProtoObject methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
_beSpecial
	<primitive: UnderBeSpecial>
	self primitiveFailed.

! !

!ProtoObject methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
_hash
	<primitive: UnderHash>
! !

!ProtoObject methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
_isBytes
	<primitive: UnderIsBytes>
! !

!ProtoObject methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
_pointersSize
	<primitive: UnderPointersSize>
! !

!ProtoObject methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
_size
	<primitive: UnderSize>
! !

!ProtoObject methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
behavior
	<primitive: Behavior>
! !

!ProtoObject methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
behavior: aBehavior
	<primitive: SetBehavior>
! !

!ProtoObject methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
class
	<primitive: Class>
! !

!ProtoObject methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
== anObject
	<primitive: Equal>
! !

!ProtoObject methodsFor:  'system' stamp: 'KenD 28/Jun/2026 13:27:38'!
perform: aSymbol withArguments: anArray
	<primitive: PerformWithArguments>
! !

!ProtoObject methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
primitiveSize
	<primitive: Size>
! !

!ProtoObject methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
primitiveAt: index
	<primitive: At>
! !

!ProtoObject methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
primitiveAt: anInteger put: anObject
	<primitive: AtPut>
! !

!ProtoObject methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
basicHash
	<primitive: Hash>
! !


