'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:38 pm'!


!Species methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
basicNew
	<primitive: New>
! !

!Species methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
basicNew: anInteger
	<primitive: NewSized>
! !

!Species methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
new
	<primitive: New>
! !

!Species methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
new: anInteger
	<primitive: NewSized>
! !

!Species methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
primitiveNewBytes: anInteger
	<primitive: NewBytes>
! !


