'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:39 pm'!
!classDefinition: #CodeSpecsModule category: #CodeSpecs!
Module subclass: #CodeSpecsModule
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'CodeSpecs'!
!CodeSpecsModule commentStamp: '<historical>' prior: 0!

    Copyright (c) 2022, Quorum Software. 
    See (MIT) license in root directory.
!

!CodeSpecsModule methodsFor:  'spec' stamp: 'KenD 28/Jun/2026 13:27:39'!
imports
	^{
		#Kernel -> #(#OrderedDictionary).
	}
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'CodeSpecsModule class' category: #CodeSpecs!
CodeSpecsModule class
	instanceVariableNames: ''!


