'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:32:25 pm'!
!classDefinition: #ConnectionReset category: 'SqueakNOS-Net-Exceptions'!
Error subclass: #ConnectionReset
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SqueakNOS-Net-Exceptions'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'ConnectionReset class' category: 'SqueakNOS-Net-Exceptions'!
ConnectionReset class
	instanceVariableNames: ''!


