'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:32:25 pm'!
!classDefinition: #NetDown category: 'SqueakNOS-Net-Exceptions'!
Error subclass: #NetDown
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SqueakNOS-Net-Exceptions'!
!NetDown methodsFor:  'description' stamp: 'KenD 28/Jun/2026 13:32:25'!
isResumable
	^ true
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'NetDown class' category: 'SqueakNOS-Net-Exceptions'!
NetDown class
	instanceVariableNames: ''!


