'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:32:25 pm'!
!classDefinition: #OutOfBandData category: 'SqueakNOS-Net-Exceptions'!
Notification subclass: #OutOfBandData
	instanceVariableNames: 'data'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SqueakNOS-Net-Exceptions'!
!OutOfBandData methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:32:25'!
data
	^ data
! !

!OutOfBandData methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:32:25'!
data: anObject
	data := anObject
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'OutOfBandData class' category: 'SqueakNOS-Net-Exceptions'!
OutOfBandData class
	instanceVariableNames: ''!


