'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:32:24 pm'!
!classDefinition: #MicroProcessor category: 'SqueakNOS-Devices-Processor'!
Object subclass: #MicroProcessor
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SqueakNOS-Devices-Processor'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'MicroProcessor class' category: 'SqueakNOS-Devices-Processor'!
MicroProcessor class
	instanceVariableNames: ''!


