'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:32:25 pm'!
!classDefinition: #LSRR category: 'SqueakNOS-Net-Options-IP'!
RecordRoute subclass: #LSRR
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SqueakNOS-Net-Options-IP'!
!LSRR methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:32:25'!
name
	^ 'LSRR'
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'LSRR class' category: 'SqueakNOS-Net-Options-IP'!
LSRR class
	instanceVariableNames: ''!

!LSRR class methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:32:25'!
type
	^ 131
! !


