'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:32:25 pm'!
!classDefinition: #SSRR category: 'SqueakNOS-Net-Options-IP'!
RecordRoute subclass: #SSRR
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SqueakNOS-Net-Options-IP'!
!SSRR methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:32:25'!
name
	^ 'SSRR'
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'SSRR class' category: 'SqueakNOS-Net-Options-IP'!
SSRR class
	instanceVariableNames: ''!

!SSRR class methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:32:25'!
type
	^ 137
! !


