'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:32:25 pm'!
!classDefinition: #TCPIdle category: 'SqueakNOS-Net-Protocols-TCP-States-Output'!
TCPOutputState subclass: #TCPIdle
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SqueakNOS-Net-Protocols-TCP-States-Output'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'TCPIdle class' category: 'SqueakNOS-Net-Protocols-TCP-States-Output'!
TCPIdle class
	instanceVariableNames: ''!


