'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:40 pm'!
!classDefinition: #RV64CodeGenerator category: #'Assembly-RISCV'!
RISCCodeGenerator subclass: #RV64CodeGenerator
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: 'RegistersRISCV'
	category: 'Assembly-RISCV'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'RV64CodeGenerator class' category: #'Assembly-RISCV'!
RV64CodeGenerator class
	instanceVariableNames: ''!


