'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:39 pm'!
!classDefinition: #STONMapWriter category: #STON!
STONStreamWriter subclass: #STONMapWriter
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'STON'!
!STONMapWriter commentStamp: '<historical>' prior: 0!

	Copyright (c) 2024 Quorum Software.
	See (MIT) license in root directory.
!

!STONMapWriter methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:27:39'!
comma
	writer comma; cr
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'STONMapWriter class' category: #STON!
STONMapWriter class
	instanceVariableNames: ''!


