'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:37 pm'!
!classDefinition: #CallbackBehavior category: #FFI!
Behavior subclass: #CallbackBehavior
	instanceVariableNames: 'nativeCode'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'FFI'!
!CallbackBehavior commentStamp: '<historical>' prior: 0!

    Copyright (c) 2020 Aucerna. 
    See (MIT) license in root directory.
!

!CallbackBehavior methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:27:37'!
nativeCode
	^nativeCode
! !

!CallbackBehavior methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:27:37'!
nativeCode: aNativeCode
	nativeCode := aNativeCode
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'CallbackBehavior class' category: #FFI!
CallbackBehavior class
	instanceVariableNames: ''!


