'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:39 pm'!
!classDefinition: #File category: #Filesystem!
FilesystemEntry subclass: #File
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Filesystem'!
!File commentStamp: '<historical>' prior: 0!

    Copyright (c) 2024, Javier Pimás. 
    See (MIT) license in root directory.
!

!File methodsFor:  'initializing' stamp: 'KenD 28/Jun/2026 13:27:39'!
/ aString
	self error: 'invalid operation'
! !

!File methodsFor:  'initializing' stamp: 'KenD 28/Jun/2026 13:27:39'!
basicPath
	self error
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'File class' category: #Filesystem!
File class
	instanceVariableNames: ''!


