'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:32:24 pm'!
!classDefinition: #ATATest category: #'SqueakNOS-Devices-Storage'!
TestCase subclass: #ATATest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SqueakNOS-Devices-Storage'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'ATATest class' category: #'SqueakNOS-Devices-Storage'!
ATATest class
	instanceVariableNames: ''!


