'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:40 pm'!
!classDefinition: #ArgumentEnvironment category: #'Powerlang-Core-SCompiler'!
StackEnvironment subclass: #ArgumentEnvironment
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Powerlang-Core-SCompiler'!
!ArgumentEnvironment methodsFor:  'private' stamp: 'KenD 28/Jun/2026 13:27:40'!
captureType
	^CaptureLocalArgument
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'ArgumentEnvironment class' category: #'Powerlang-Core-SCompiler'!
ArgumentEnvironment class
	instanceVariableNames: ''!


