'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:41 pm'!
!classDefinition: #InlinedArgEnvironment category: #'Powerlang-Core-SCompiler'!
StackEnvironment subclass: #InlinedArgEnvironment
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Powerlang-Core-SCompiler'!
!InlinedArgEnvironment methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:27:41'!
captureType
	^CaptureInlinedArgument
! !

!InlinedArgEnvironment methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:27:41'!
isInlinedArgument
	^true
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'InlinedArgEnvironment class' category: #'Powerlang-Core-SCompiler'!
InlinedArgEnvironment class
	instanceVariableNames: ''!


