'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:40 pm'!
!classDefinition: #LocalEnvironment category: #'Powerlang-Core-SCompiler'!
Object subclass: #LocalEnvironment
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: 'ClosureElementTypes'
	category: 'Powerlang-Core-SCompiler'!
!LocalEnvironment methodsFor:  'testing' stamp: 'KenD 28/Jun/2026 13:27:40'!
isInlinedArgument
	^false
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'LocalEnvironment class' category: #'Powerlang-Core-SCompiler'!
LocalEnvironment class
	instanceVariableNames: ''!


