'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:40 pm'!
!classDefinition: #StackEnvironment category: #'Powerlang-Core-SCompiler'!
LocalEnvironment subclass: #StackEnvironment
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Powerlang-Core-SCompiler'!
!StackEnvironment methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:27:40'!
index
	^nil
! !

!StackEnvironment methodsFor:  'private' stamp: 'KenD 28/Jun/2026 13:27:40'!
isStack
	^true
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'StackEnvironment class' category: #'Powerlang-Core-SCompiler'!
StackEnvironment class
	instanceVariableNames: ''!


