'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:32:25 pm'!
!classDefinition: #MemoryBlockDeviceTest category: 'SqueakNOS-Storage-Tests'!
TestCase subclass: #MemoryBlockDeviceTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SqueakNOS-Storage-Tests'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'MemoryBlockDeviceTest class' category: 'SqueakNOS-Storage-Tests'!
MemoryBlockDeviceTest class
	instanceVariableNames: ''!


