'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:41 pm'!
!classDefinition: #JsonBooleanSchema category: #JSON!
JsonPrimitiveSchema subclass: #JsonBooleanSchema
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'JSON'!
!JsonBooleanSchema commentStamp: '<historical>' prior: 0!

	Copyright (c) 2020 Aucerna.
	See (MIT) license in root directory.
!

!JsonBooleanSchema methodsFor:  'testing' stamp: 'KenD 28/Jun/2026 13:27:41'!
isBooleanSchema
	^true
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'JsonBooleanSchema class' category: #JSON!
JsonBooleanSchema class
	instanceVariableNames: ''!


