'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:32:24 pm'!
!classDefinition: #DevelopmentModule category: #Webside!
Module subclass: #DevelopmentModule
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Webside'!
!DevelopmentModule commentStamp: '<historical>' prior: 0!

	Copyright (c) 2025, Javier Pimás.
	See (MIT) license in root directory.
!

!DevelopmentModule methodsFor:  'spec' stamp: 'KenD 28/Jun/2026 13:32:24'!
imports
	^{
		#Kernel -> #(ProtoObject)
	}
! !

!DevelopmentModule methodsFor:  'initializing' stamp: 'KenD 28/Jun/2026 13:32:24'!
main: arguments

! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'DevelopmentModule class' category: #Webside!
DevelopmentModule class
	instanceVariableNames: ''!


