'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:39 pm'!
!classDefinition: #ImageSegmentBuilderModule category: #ImageSegmentBuilder!
Module subclass: #ImageSegmentBuilderModule
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'ImageSegmentBuilder'!
!ImageSegmentBuilderModule commentStamp: '<historical>' prior: 0!

	Copyright (c) 2022, Javier Pimás.
	See (MIT) license in root directory.
!

!ImageSegmentBuilderModule methodsFor:  'spec' stamp: 'KenD 28/Jun/2026 13:27:39'!
imports
	^{
		#Kernel -> {
			#Behavior. #Boolean. #False. #HashTable. #IdentityDictionary. #IdentitySet. #KernelModule. 
			#Module. #Symbol. #SymbolicReference. #True. #UndefinedObject
		}
	}
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'ImageSegmentBuilderModule class' category: #ImageSegmentBuilder!
ImageSegmentBuilderModule class
	instanceVariableNames: ''!


