'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:32:25 pm'!
!classDefinition: #IGRPPacket category: 'SqueakNOS-Net-Packets'!
Packet subclass: #IGRPPacket
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SqueakNOS-Net-Packets'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'IGRPPacket class' category: 'SqueakNOS-Net-Packets'!
IGRPPacket class
	instanceVariableNames: ''!

!IGRPPacket class methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:32:25'!
protocol
	^ 9
! !


