'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:32:25 pm'!
!classDefinition: #IPv6Packet category: 'SqueakNOS-Net-Packets'!
IPPacket subclass: #IPv6Packet
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SqueakNOS-Net-Packets'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'IPv6Packet class' category: 'SqueakNOS-Net-Packets'!
IPv6Packet class
	instanceVariableNames: ''!

!IPv6Packet class methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:32:25'!
etherType
	^ 16r86DD
! !


