'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:32:25 pm'!
!classDefinition: #RDPPacket category: 'SqueakNOS-Net-Packets'!
Packet subclass: #RDPPacket
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SqueakNOS-Net-Packets'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'RDPPacket class' category: 'SqueakNOS-Net-Packets'!
RDPPacket class
	instanceVariableNames: ''!

!RDPPacket class methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:32:25'!
protocol
	^ 27
! !


