'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:39 pm'!


!Object methodsFor:  '*IR' stamp: 'KenD 28/Jun/2026 13:27:39'!
isBinaryConstantOperation
	^false
! !

!Object methodsFor:  '*IR' stamp: 'KenD 28/Jun/2026 13:27:39'!
isBinaryVariableOperation
	^false
! !

!Object methodsFor:  '*IR' stamp: 'KenD 28/Jun/2026 13:27:39'!
isTernaryOperation
	^false
! !

!Object methodsFor:  '*IR' stamp: 'KenD 28/Jun/2026 13:27:39'!
isUnaryOperation
	^false
! !

!Object methodsFor:  '*IR' stamp: 'KenD 28/Jun/2026 13:27:39'!
primitivePrintString
	^self printString
! !


