'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:39 pm'!
!classDefinition: #OUseVariable category: #IR!
OInstruction subclass: #OUseVariable
	instanceVariableNames: 'binding'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'IR'!
!OUseVariable commentStamp: '<historical>' prior: 0!

    Copyright (c) 2020 Aucerna.
    See (MIT) license in root directory.
!

!OUseVariable methodsFor:  'unclassified' stamp: 'KenD 28/Jun/2026 13:27:39'!
binding
	^binding
! !

!OUseVariable methodsFor:  'unclassified' stamp: 'KenD 28/Jun/2026 13:27:39'!
binding: aBinding
	binding := aBinding
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'OUseVariable class' category: #IR!
OUseVariable class
	instanceVariableNames: ''!


