'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:38 pm'!
!classDefinition: #LMRArrayedCollection category: #Kernel!
ArrayedCollection subclass: #LMRArrayedCollection
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Kernel'!
!LMRArrayedCollection commentStamp: '<historical>' prior: 0!

	Copyright (c) 2023, Javier Pimás.
	See (MIT) license in root directory.
!

!LMRArrayedCollection methodsFor:  '*Primitives' stamp: 'KenD 28/Jun/2026 13:27:38'!
size
	^self primitiveSize
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'LMRArrayedCollection class' category: #Kernel!
LMRArrayedCollection class
	instanceVariableNames: ''!


