'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:38 pm'!
!classDefinition: #LMRCharacterArray category: #Kernel!
CharacterArray subclass: #LMRCharacterArray
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Kernel'!
!LMRCharacterArray commentStamp: '<historical>' prior: 0!

	Copyright (c) 2023, Javier Pimás.
	See (MIT) license in root directory.
!

!LMRCharacterArray methodsFor:  'private' stamp: 'KenD 28/Jun/2026 13:27:38'!
primitiveSize
	^self _size
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'LMRCharacterArray class' category: #Kernel!
LMRCharacterArray class
	instanceVariableNames: ''!


