'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:38 pm'!
!classDefinition: #LMRModule category: #Kernel!
Module subclass: #LMRModule
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Kernel'!
!LMRModule commentStamp: '<historical>' prior: 0!

	Copyright (c) 2024, Javier Pimás.
	See (MIT) license in root directory.
!

!LMRModule methodsFor:  'spec' stamp: 'KenD 28/Jun/2026 13:27:38'!
imports
	^{
		#Kernel -> #(ArrayedCollection CharacterArray Closure Float ProtoObject Species Symbol)
	}
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'LMRModule class' category: #Kernel!
LMRModule class
	instanceVariableNames: ''!


