'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:37 pm'!


!Object methodsFor:  '*SUnit' stamp: 'KenD 28/Jun/2026 13:27:37'!
sunitAddDependent: anObject
	self addDependent: anObject
! !

!Object methodsFor:  '*SUnit' stamp: 'KenD 28/Jun/2026 13:27:37'!
sunitChanged: aspect
	self changed: aspect
! !

!Object methodsFor:  '*SUnit' stamp: 'KenD 28/Jun/2026 13:27:37'!
sunitRemoveDependent: anObject
	self removeDependent: anObject
! !


