'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:37 pm'!
!classDefinition: #TestSkipped category: #SUnit!
Notification subclass: #TestSkipped
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SUnit'!
!TestSkipped commentStamp: '<historical>' prior: 0!

	Copyright (c) 2021 Aucerna.
	See (MIT) license in root directory.
!

!TestSkipped methodsFor:  'testing' stamp: 'KenD 28/Jun/2026 13:27:37'!
isResumable
	^false
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'TestSkipped class' category: #SUnit!
TestSkipped class
	instanceVariableNames: ''!


