'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:39 pm'!
!classDefinition: #BootstrapDictionary category: #Kernel!
Object subclass: #BootstrapDictionary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Kernel'!
!BootstrapDictionary commentStamp: '<historical>' prior: 0!

    Copyright (c) 2020 Aucerna. 
    See (MIT) license in root directory.
!

!BootstrapDictionary methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:27:39'!
at: key
	<primitive: BootstrapDictAt>
! !

!BootstrapDictionary methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:27:39'!
at: key put: value
	<primitive: BootstrapDictAtPut>
! !

!BootstrapDictionary methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:27:39'!
beConstantPool
	<primitive: BootstrapDictBeConstant>
! !

!BootstrapDictionary methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:27:39'!
keys
	<primitive: BootstrapDictKeys>
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'BootstrapDictionary class' category: #Kernel!
BootstrapDictionary class
	instanceVariableNames: ''!


