'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:38 pm'!
!classDefinition: #EndOfStream category: #Kernel!
Error subclass: #EndOfStream
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Kernel'!
!EndOfStream commentStamp: '<historical>' prior: 0!

    Copyright (c) 2020 Aucerna.
    See (MIT) license in root directory.
!

!EndOfStream methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:27:38'!
defaultDescription
	^'end of stream'
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'EndOfStream class' category: #Kernel!
EndOfStream class
	instanceVariableNames: ''!


