'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:38 pm'!
!classDefinition: #Halt category: #Kernel!
Exception subclass: #Halt
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Kernel'!
!Halt commentStamp: '<historical>' prior: 0!

    Copyright (c) 2020 Aucerna. 
    See (MIT) license in root directory.
!

!Halt methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:27:38'!
defaultDescription
	^'halt'
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Halt class' category: #Kernel!
Halt class
	instanceVariableNames: ''!


