'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:38 pm'!
!classDefinition: #StackOverflow category: #Kernel!
Error subclass: #StackOverflow
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Kernel'!
!StackOverflow commentStamp: '<historical>' prior: 0!

    Copyright (c) 2020 Aucerna. 
    See (MIT) license in root directory.
!

!StackOverflow methodsFor:  'accessing' stamp: 'KenD 28/Jun/2026 13:27:38'!
defaultDescription
	^'Stack overflow'
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'StackOverflow class' category: #Kernel!
StackOverflow class
	instanceVariableNames: ''!


