'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:32:25 pm'!
!classDefinition: #Ping category: 'SqueakNOS-Net-MissingClass'!
Object subclass: #Ping
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SqueakNOS-Net-MissingClass'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Ping class' category: 'SqueakNOS-Net-MissingClass'!
Ping class
	instanceVariableNames: ''!


