'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:32:25 pm'!
!classDefinition: #TCPSynScanner category: 'SqueakNOS-Net-MissingClass'!
Object subclass: #TCPSynScanner
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SqueakNOS-Net-MissingClass'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'TCPSynScanner class' category: 'SqueakNOS-Net-MissingClass'!
TCPSynScanner class
	instanceVariableNames: ''!


