'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:32:25 pm'!
!classDefinition: #TraceRoute category: 'SqueakNOS-Net-MissingClass'!
Object subclass: #TraceRoute
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SqueakNOS-Net-MissingClass'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'TraceRoute class' category: 'SqueakNOS-Net-MissingClass'!
TraceRoute class
	instanceVariableNames: ''!


