'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:37 pm'!
!classDefinition: #TOMLModule category: #TOML!
Module subclass: #TOMLModule
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'TOML'!
!TOMLModule commentStamp: '<historical>' prior: 0!

    Copyright (c) 2026, Javier Pimás.
    See (MIT) license in root directory.
!

!TOMLModule methodsFor:  'spec' stamp: 'KenD 28/Jun/2026 13:27:37'!
imports
	^{
		#Kernel -> #(Character Error OrderedDictionary).
	}
! !


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'TOMLModule class' category: #TOML!
TOMLModule class
	instanceVariableNames: ''!


