'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:38 pm'!
!classDefinition: #HTTPObject category: #CPPHTTPServer!
ExternalObject subclass: #HTTPObject
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'CPPHTTPServer'!
!HTTPObject commentStamp: '<historical>' prior: 0!

    Copyright (c) 2025, Javier Pimás. 
    See (MIT) license in root directory.
!


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'HTTPObject class' category: #CPPHTTPServer!
HTTPObject class
	instanceVariableNames: ''!


