'From Cuis7.9 [latest update: #7998] on 28 June 2026 at 1:27:39 pm'!
!classDefinition: #DispatchSite category: #Kernel!
Object subclass: #DispatchSite
	instanceVariableNames: 'instructions token cache tally format'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Kernel'!
!DispatchSite commentStamp: '<historical>' prior: 0!

    Copyright (c) 2022 Quorum Software. 
    See (MIT) license in root directory.
!


"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'DispatchSite class' category: #Kernel!
DispatchSite class
	instanceVariableNames: ''!


