# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - "**"
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  # we build most things from ubuntu: linux specific ones and also portable things (i.e. js-vm)
  build-linux:
    name: Build and Test bootstrap - ${{matrix.go-version}} ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Fetch at least 2 commits so that Iceberg doesn't break
      run: git fetch --unshallow

    - name: Fetch at main so that Iceberg doesn't break
      run: git fetch origin main

    - name: Compile
      run: make js

    - name: "Determine tag"
      if: "${{ github.event_name }} == 'push' && ${{ github.ref_type }} == 'tag'"
      run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"
      shell: "bash"

    - name: Package JS
      if: matrix.os == 'ubuntu-latest'
      run: make release-js

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/eggjs-${{env.RELEASE_TAG}}.tar.gz,build/eggjs-${{env.RELEASE_TAG}}.zip"
#        bodyFile: "body.md" 

    - name: Package CPP
      run: make release-cpp

    - name: Upload cpp vm for Linux
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/eggcpp-${{ env.RELEASE_TAG }}.tar.gz"

  #only needed for windows-specific stuff (i.e. cpp-vm exe)
  build-win:
    name: Build and Test bootstrap - ${{matrix.go-version}} ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Fetch at least 2 commits so that Iceberg doesn't break
      run: git fetch --unshallow

    - name: Fetch at main so that Iceberg doesn't break
      run: git fetch origin main

    - name: "Determine tag"
      if: "${{ github.event_name }} == 'push' && ${{ github.ref_type }} == 'tag'"
      run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"
      shell: "bash"

    - name: Package CPP
      run: make release-cpp

    - name: Upload cpp vm for Windows
      if: matrix.os == 'windows-latest'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/eggcpp-${{ env.RELEASE_TAG }}.zip"
